version: "3.8"

services:
  # PostgreSQL Database with TimescaleDB
  postgres:
    image: timescale/timescaledb:latest-pg15
    container_name: boursa-postgres-prod
    restart: unless-stopped
    environment:
      - POSTGRES_DB=boursa_vision
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/backups
    networks:
      - boursa-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d boursa_vision"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: boursa-redis-prod
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 1g --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    networks:
      - boursa-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Backend API (Production)
  backend:
    build:
      context: ../backend
      dockerfile: ../docker/Dockerfile.backend
      target: production
    container_name: boursa-backend-prod
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/boursa_vision
      - REDIS_URL=redis://redis:6379/0
      - ENVIRONMENT=production
      - LOG_LEVEL=WARNING
      - API_V1_STR=/api/v1
      - SECRET_KEY=${SECRET_KEY}
      - ACCESS_TOKEN_EXPIRE_MINUTES=720
      - YFINANCE_RATE_LIMIT=50
      - YFINANCE_BATCH_SIZE=100
      # Configuration Cache Intelligent
      - CACHE_MODE=production
      - CACHE_DEBUG=false
      - YFINANCE_REQUESTS_PER_MINUTE=150
      - YFINANCE_REQUESTS_PER_HOUR=5000
      - MAX_CONCURRENT_REQUESTS=50
      - BATCH_SIZE=100
      - MAX_MEMORY_USAGE_MB=2048
      - MAX_TIMELINES_IN_MEMORY=500
      - ENABLE_METRICS=true
      - REDIS_URL=redis://redis:6379/0
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
      - SECRET_KEY=${SECRET_KEY}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES:-1440}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - CORS_ORIGINS=${CORS_ORIGINS}
    volumes:
      - backend_logs:/app/logs
    networks:
      - boursa-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 60s
      timeout: 10s
      retries: 3

  # Cache Intelligent YFinance (Production)
  cache-system:
    build:
      context: ../backend
      dockerfile: ../docker/Dockerfile.cache
      target: cache-production
    container_name: boursa-cache-system-prod
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/boursa_vision
      - REDIS_URL=redis://redis:6379/2
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - ENVIRONMENT=production
      - LOG_LEVEL=WARNING
      - CACHE_MODE=production
      - CACHE_DEBUG=false
      - YFINANCE_REQUESTS_PER_MINUTE=150
      - YFINANCE_REQUESTS_PER_HOUR=5000
      - MAX_CONCURRENT_REQUESTS=50
      - BATCH_SIZE=100
      - MAX_MEMORY_USAGE_MB=2048
      - MAX_TIMELINES_IN_MEMORY=500
      - ENABLE_METRICS=true
      - ENABLE_PREFETCHING=true
    ports:
      - "8001:8001"
    volumes:
      - cache_data:/app/cache_data
      - cache_logs:/app/logs
      - cache_metrics:/app/metrics
    networks:
      - boursa-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 3G
          cpus: '2.0'
        reservations:
          memory: 2G
          cpus: '1.0'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Frontend PWA (Production)
  frontend:
    build:
      context: ../frontend
      dockerfile: ../docker/Dockerfile.frontend
      target: production
      args:
        - VITE_API_BASE_URL=${VITE_API_BASE_URL}
        - VITE_WS_URL=${VITE_WS_URL}
    container_name: boursa-frontend-prod
    restart: unless-stopped
    networks:
      - boursa-network

  # Celery Worker (Production)
  celery-worker:
    build:
      context: ../backend
      dockerfile: ../docker/Dockerfile.backend
      target: production
    container_name: boursa-celery-worker-prod
    restart: unless-stopped
    command: poetry run celery -A src.infrastructure.background.celery_app worker --loglevel=info --concurrency=4
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/boursa_vision
      - REDIS_URL=redis://redis:6379/0
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
    volumes:
      - backend_logs:/app/logs
    networks:
      - boursa-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  # Celery Beat (Production)
  celery-beat:
    build:
      context: ../backend
      dockerfile: ../docker/Dockerfile.backend
      target: production
    container_name: boursa-celery-beat-prod
    restart: unless-stopped
    command: poetry run celery -A src.infrastructure.background.celery_app beat --loglevel=info
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/boursa_vision
      - REDIS_URL=redis://redis:6379/0
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
    volumes:
      - backend_logs:/app/logs
    networks:
      - boursa-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  # Nginx Reverse Proxy with SSL
  nginx:
    image: nginx:alpine
    container_name: boursa-nginx-prod
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - nginx_logs:/var/log/nginx
    networks:
      - boursa-network
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  backend_logs:
    driver: local
  cache_data:
    driver: local
  cache_logs:
    driver: local
  cache_metrics:
    driver: local
  nginx_logs:
    driver: local

networks:
  boursa-network:
    driver: bridge
